feature: add emoji at the front of callout
remirror/remirror pull request #980
Opened 2021-06-22 14:28 UTC by Gaaaga

### Description

Add configurable emoji to callouts. closed #871

### Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.
- [x] My code follows the code style of this project and `pnpm fix` completed successfully.
- [x] I have updated the documentation where necessary.
- [x] New code is unit tested and all current tests pass when running `pnpm test`.

### Screenshots

![callout with emoji](https://user-images.githubusercontent.com/16329365/122939944-a0c18100-d3a6-11eb-9ecf-969ef291a117.png)

I truly appreciate @ocavue 's patient guidance, helping me dive right in the remirror project and have a better understanding of how it works.

2021-06-23 03:20 UTC, ocavue commented on packages/remirror__extension-callout/src/callout-extension.ts
> +      const emoji = renderEmoji(node, view, pos);
```suggestion
      const dom = document.createElement('div');
      const contentDOM = document.createElement('div');
      const emojiDOM = document.createElement('div');
      const { renderEmoji } = this.options;
      const emoji = renderEmoji(node, view, getPos as () => number);
```

2021-06-23 03:25 UTC, ocavue commented on packages/remirror__extension-callout/src/callout-extension.ts
> +        emoji: { default: '💡' },
Maybe it's better to allow users to change the default emoji with extension options, like `defaultType` above.

2021-06-23 03:26 UTC, ocavue commented on packages/remirror__extension-callout/src/callout-extension.ts
> +        const { type, emoji, ...rest } = omitExtraAttributes(node.attrs, extra);
This variable is not used here

2021-06-23 03:33 UTC, ocavue commented on packages/remirror__extension-callout/src/callout-extension.ts
> +import { ExtensionCalloutTheme } from '../../remirror__core/node_modules/@remirror/theme/src';
```suggestion
import { ExtensionCalloutTheme } from '@remirror/theme';
```

You may need to add `@remirror/theme` to `packages/remirror__extension-callout/package.json`.

2021-06-23 03:55 UTC, ocavue commented
The copy-and-paste of emoji doesn't work. In the video below, the background was copied but the emoji wasn't.


https://user-images.githubusercontent.com/24715727/123033083-ba4fe080-d419-11eb-8da3-98a8c6ac4931.mov


We could do it by adding a new data attribute to the DOM. Something like below should work.

```diff
      parseDOM: [
        {
          tag: `div[${dataAttributeType}]`,
          getAttrs: (node) => {
            if (!isElementDomNode(node)) {
              return false;
            }

            const rawType = node.getAttribute(dataAttributeType);
            const type = getCalloutType(rawType, validTypes, defaultType);
+           const emoji = node.getAttribute(dataAttributeEmoji);
            const content = node.textContent;
-           return { ...extra.parse(node), type, content };
+           return { ...extra.parse(node), type, emoji, content };
          },
        },
        ...(override.parseDOM ?? []),
      ],
      toDOM: (node) => {
        const { type, emoji, ...rest } = omitExtraAttributes(node.attrs, extra);
-       const attributes = { ...extra.dom(node), ...rest, [dataAttributeType]: type };
+       const attributes = { ...extra.dom(node), ...rest, [dataAttributeType]: type, [dataAttributeEmoji]: emoji };
        return ['div', attributes, 0];
      },
```

2021-06-23 16:23 UTC, Gaaaga commented
@ocavue   Thanks for your review, solved.

2021-06-24 10:58 UTC, ocavue approved these changes

2021-06-24 11:00 UTC, ocavue commented
@whawker Do you have any time to review this PR. I have checked the code but would like to hear your opinion. You can find a complete example in the storybook.

2021-06-24 11:16 UTC, ifiokjr commented on .changeset/heavy-fishes-hammer.md
> +Added configurable emoji at the front of callout extension. Added a new type 'blank' to callout extension.
```suggestion
- Added configurable emoji to the start of the `CalloutExtension`. 
- Added a new type 'blank' to the `CalloutExtension`.
```

2021-06-24 11:21 UTC, ifiokjr requested changes
Great stuff 👍 

Just one minor change to make in the changeset, and it'll be ready to merge.

2021-06-24 11:54 UTC, Gaaaga commented
Thanks for the review, @ifiokjr !

2021-06-24 13:20 UTC, ifiokjr approved these changes
I'm happy to merge this now.

2021-06-24 13:20 UTC, ifiokjr commented
/publish

2021-06-24 13:40 UTC, merged

2021-06-28 20:50 UTC, whawker commented
@Gaaaga thanks for this!! Apologies for the very late reply, I've been a bit snowed under with my own work.

The code looks good, just one thing seems missing to me - I feel the callout extension should expose a command to change the emoji, rather than expecting the user to use `setNodeMarkup`.

```ts
const transaction = view.state.tr.setNodeMarkup(getPos(), undefined, {
  emoji: selection.emoji,
  type,
});
view.dispatch(transaction);
```

In my mind the expected behaviour is to import Remirror's `useCommands` hook and utilise a dedicated command.

```ts
const { toggleCalloutEmoji } = useCommands(); 
```

As a reference, I've created [this CodeSandbox](https://codesandbox.io/s/remirror-pr-000-pr70635-forked-3dss6?file=/src/Emojis.tsx) which uses `customDispatch` from `useCommands`, but ideally it would use an exposed command like above.

2021-06-29 07:00 UTC, Gaaaga commented
Thanks @whawker ,  very constructive advice! I'm gonna take your advice and open another PR to improve it :)